config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/todos', to: 'todos#index'
  get '/todos/list', to: 'todos#list' 
  get '/todos/new', to: 'todos#new'
  post '/todos', to: 'todos#create'
  get  '/todos/:id', to: 'todos#show', as: 'todo'
  get  '/todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch '/todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get '/todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
        
    end

    def create
        @todo = Todo.new(todo_params)
        @todo.description
        @todo.save
        redirect_to todos_path
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def edit
        @todo = Todo.find(params[:id])  
    end



    def update
        @todo = Todo.find(params[:id])  
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo = Todo.find(params[:id])  
        @todo.destroy
        redirect_to todos_path
    end

    def complete
        @todo = Todo.find(params[:id]) 
        @todo.completed = true
        @todo.save
        redirect_to todos_path
    end

    def list
        @completed = Todo.where(completed: true)
        @uncompleted = Todo.where(completed: false)
    end

    private
        def todo_params
            params.require(:todo).permit(:description, :completed)
        end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300|PT+Mono|Questrial|Roboto+Slab|Roboto:300|Teko:700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">


    
  </head>

  <body>
      
        <nav class="navbar navbar-inverse navbar-fixed-top">
        
        <i class="navbar-brand fa fa-2x fa-tasks" style="color:white; opacity:0.9;"><a style="font-family:'Teko'; font-size:34px;color:white; opacity:0.9;"> 2DO</a><a style=" navbar-brand font-family:'Open Sans'; font-size:30px;color:white; opacity:0.9;">   |  </a></i>
            <div class="container" style="">
            <%= link_to 'Inicio', todos_path, :class => 'navbar-text', :style =>  'color:white; opacity:0.9;'%>
            <%= link_to 'Lista', todos_list_path, :class => 'navbar-text', :style =>  'color:white; opacity:0.9;' %>
            <%= link_to 'Agregar tarea', todos_new_path, :class => 'navbar-text',:style =>  'color:white; opacity:0.9;' %>
            </div>
        </nav> 
        <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/todos/edit.html.erb
<div class="col-sm-4"></div>
<div class="container col-sm-4">
<div class="well text-center">

<%= form_with(model: @todo, local: true) do |f| %>
 <%= f.label :Tarea, :class => 'title-dos'%>
 <%= f.text_field :description, :class => 'form-control' %>
 <br>
 <%= f.submit :Actualizar, :class => 'btn btn-success' %>
<% end %>
</div>
</div>

app/views/todos/index.html.erb
        
        
<div class="container ">
<div class="col-md-8 col-md-offset-2   ">
    <% @todos.each do |todo| %>
    <div class="well ">
    
    <% if todo.completed == true %>
    <div class="row align-items-center">
    <div class="col-md-1"></div>
      <div class="col-md-7 ">
        <p class="display-4 title" style="opacity: 0.5;"><s><%= todo.description%></s></p>
        <p class="cr_ag">Created <%= time_ago_in_words todo.created_at %> ago</p>
      </div>      

      <div class="col-md-1 text-center pad_btn">
        <p style="font-size: 20px;"><%= link_to todo_path(todo.id) do%></p>
        <i class="fas fa-lg fa-eye" style="color:black"></i>
        <% end %>
      </div>  
      <div class="col-md-1 text-center pad_btn">
        <p><%= link_to edit_todo_path(todo.id) do%></p>
        <i class="fa fa-lg fa-pen" style="color:black"></i>
        <% end %>
      </div>  
      <div class="col-md-1 text-center pad_btn">
        <p><%= link_to todo, method: :delete do %></p>
        <i class="fa fa-lg fa-trash" style="color:red; opacity: 0.7;"></i>
        <% end %>
      </div>  
      
    </div>
    <% else %>
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-6">
                <p class="title"><%= todo.description%></p>
                <p class="cr_ag">Created <%= time_ago_in_words todo.created_at %> ago</p>
            </div>    
                
            <div class="col-md-1 text-center pad_btn">    
                <p><%= link_to complete_todo_path(todo.id) do%></p>
                <i class="fa fa-lg fa-check" style="color:black" ></i>
                <% end %>
            </div>    
                
            <div class="col-md-1 text-center pad_btn pad_btn"> 
                <p style="font-size: 20px;"><%= link_to todo_path(todo.id) do%></p>
                <i class="fas fa-lg fa-eye" style="color:black"></i>
                <% end %>
            </div>
            <div class="col-md-1 text-center pad_btn pad_btn">                
                <p><%= link_to edit_todo_path(todo.id) do%></p>
                <i class="fa fa-lg fa-pen" style="color:black"></i>
                <% end %>
            </div>    
            <div class="col-md-1 text-center pad_btn">                
                <p><%= link_to todo, method: :delete do %></p>
                <i class="fa fa-lg fa-trash" style="color:red; opacity: 0.7;" ></i>
                <% end %>
             </div>   
             <div class="col-md-1"></div>
                
        </div>
        
</div>
    
    
    
    <% end %>
<% end %>
</div>
 </div> 
        <div class="col-md-6 col-md-offset-3   text-center">
            <p style='op'><%= link_to todos_new_path do%></p>
            <i class="fa fa-4x fa-plus-circle" style="color:red; opacity:0.7;"></i>
            <% end %>
            </div>
            
          
</div>
            
        

        

    

app/views/todos/list.html.erb
<div class="container">
<div class="col-sm-6 well">
<h2>Tareas realizadas</h2>
    <% @completed.each do |c|%>
    <h5>• <%= c.description %></h5>
    <% end %>
</div>


<div class="col-sm-6 well">
<h2>Tareas no realizadas</h2>
    <% @uncompleted.each do |c|%>
    <h5>• <%= c.description %></h5>
    <% end %>
</div>
</div>

app/views/todos/new.html.erb
<div class="container">
<div class="col-sm-4"></div>
<div class="well text-center col-sm-4">
<%= form_with(model: @todo, local: true) do |f| %>
 <%= f.label 'Tarea:', :class => 'title-dos' %>
 <%= f.text_field :description, :class => 'form-control'%>
 <%= f.check_box :completed,:style => 'visibility: hidden' %>

<br>

 <%= f.submit :crear, :class => 'btn btn-danger' %>
<% end %>
</div>
</div>

app/views/todos/show.html.erb
<div class="well text-center">
<p class="title"><%= @todo.description %></p>
<p class="cr_ag">Created <%= time_ago_in_words @todo.created_at %></p>
<p><%= link_to todos_path do %></p>
<i class="fa fa-3x fa-arrow-circle-left" style="color:red;opacity:.8;"></i>
<% end %>
</div>